"""added ordr, order_fill and payout_log table 2

Revision ID: 03d7b314189b
Revises: b5b59ce52699
Create Date: 2025-07-30 23:07:14.100140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '03d7b314189b'
down_revision: Union[str, Sequence[str], None] = 'b5b59ce52699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.Integer(), nullable=False),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', name='ordertype'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PARTIAL', 'FILLED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('amount_usdc', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('shares', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount_usdc >= 0', name='_amount_usdc_non_negative'),
    sa.CheckConstraint('shares >= 0', name='_order_shares_non_negative'),
    sa.ForeignKeyConstraint(['market', 'token'], ['market_outcomes.market', 'market_outcomes.token'], ),
    sa.ForeignKeyConstraint(['user_name'], ['users.name'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('payout_logs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shares_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market', 'token'], ['market_outcomes.market', 'market_outcomes.token'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.name'], ),
    sa.PrimaryKeyConstraint('user_id', 'market', 'token')
    )
    op.create_table('order_fills',
    sa.Column('fill_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fill_shares', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('filled_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('fill_price >= 0', name='_fill_price_non_negative'),
    sa.CheckConstraint('fill_shares >= 0', name='_fill_shares_non_negative'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('fill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_fills')
    op.drop_table('payout_logs')
    op.drop_table('orders')
    # ### end Alembic commands ###
