"""added ordr, order_fill and payout_log table

Revision ID: b5b59ce52699
Revises: 4f8ecd19b36b
Create Date: 2025-07-30 23:05:50.223952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b5b59ce52699'
down_revision: Union[str, Sequence[str], None] = '4f8ecd19b36b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
