"""removed question sslug in market

Revision ID: e1a0b8671c1e
Revises: 03d7b314189b
Create Date: 2025-07-31 03:09:50.659880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e1a0b8671c1e'
down_revision: Union[str, Sequence[str], None] = '03d7b314189b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markets', 'market_slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('market_slug', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
